<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-10-16">

<title>Síntomas vocales en profesores</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="limpio_files/libs/clipboard/clipboard.min.js"></script>
<script src="limpio_files/libs/quarto-html/quarto.js"></script>
<script src="limpio_files/libs/quarto-html/popper.min.js"></script>
<script src="limpio_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="limpio_files/libs/quarto-html/anchor.min.js"></script>
<link href="limpio_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="limpio_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="limpio_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="limpio_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="limpio_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lectura-y-limpieza-de-los-datos" id="toc-lectura-y-limpieza-de-los-datos" class="nav-link active" data-scroll-target="#lectura-y-limpieza-de-los-datos">Lectura y limpieza de los datos</a></li>
  <li><a href="#p7-el-cuidado-de-voz-mejora-la-calidad-de-la-misma-cuál-es-la-mejor-medida" id="toc-p7-el-cuidado-de-voz-mejora-la-calidad-de-la-misma-cuál-es-la-mejor-medida" class="nav-link" data-scroll-target="#p7-el-cuidado-de-voz-mejora-la-calidad-de-la-misma-cuál-es-la-mejor-medida">P7: ¿El cuidado de voz mejora la calidad de la misma? ¿Cuál es la mejor medida?</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Síntomas vocales en profesores</h1>
<p class="subtitle lead">20582- Análisis de Datos para el GMAT</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><strong>Grupo escuderia_ferrrari: Álvaro Velasco Sobrino, Carlos Bayes Liébana, Miquel Rivas Vanrell</strong></p>
<section id="lectura-y-limpieza-de-los-datos" class="level2">
<h2 class="anchored" data-anchor-id="lectura-y-limpieza-de-los-datos">Lectura y limpieza de los datos</h2>
<p>Leemos los datos del fichero “Salut_Vocal_anonimizada.csv” y cambiamos los nombres de las variables.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 185
Columns: 37
$ ID                       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…
$ Importancia_voz          &lt;int&gt; 10, 10, 10, 10, 10, 10, 9, 9, 10, 10, 9, 10, …
$ Sexo                     &lt;chr&gt; "Femení", "Femení", "Masculí", "Femení", "Fem…
$ Lugar_trabajo            &lt;chr&gt; "Palma, Llucmajor, Algaida, Santa Eugènia, Ma…
$ Cuerpo_docente           &lt;chr&gt; "Formació Professional", "Educació Secundària…
$ Edad                     &lt;chr&gt; "Entre 36 i 50", "Entre 36 i 50", "Entre 36 i…
$ Actividas_fisica         &lt;chr&gt; "Més de 150 min. per setmana", "Més de 150 mi…
$ Importancia_deporte      &lt;int&gt; 10, 10, 10, 8, 10, 10, 10, 7, 10, 10, 7, 9, 7…
$ Calidad_sueño            &lt;chr&gt; "Dorm bé i em despert descansat", "Dorm bé pe…
$ Cafe                     &lt;chr&gt; "Diàriament", "Ocasionalment", "Diàriament", …
$ Tabaco                   &lt;chr&gt; "Diariament", "No", "No", "Anteriorment (exfu…
$ Alcohol                  &lt;chr&gt; "Ocasionalment", "Ocasionalment", "Setmanalme…
$ Bebida_gas               &lt;chr&gt; "Mai", "Ocasionalment", "Diàriament", "Ocasio…
$ Dieta_saludable          &lt;int&gt; 8, 6, 9, 6, 10, 10, 8, 8, 8, 8, 9, 9, 8, 7, 7…
$ Diagnostico              &lt;chr&gt; "Cap de les esmentades anteriorment", "Cap de…
$ Patologia                &lt;chr&gt; "", "", "", "", "Asma, al·lergia", "", "", ""…
$ Diagnostico_especialista &lt;chr&gt; "No", "Si", "No", "Si", "No", "Si", "No", "No…
$ Sintomas                 &lt;chr&gt; "Mucositat", "Fatiga vocal", "Veu ronca, esca…
$ Operacion                &lt;chr&gt; "No", "No", "No", "No", "No", "No", "No", "No…
$ Tiempo_alteracion        &lt;chr&gt; "No tenc cap alteració de la veu.", "Va comen…
$ Baja_voz                 &lt;chr&gt; "No, mai he estat de baixa per un problema de…
$ Baja_larga               &lt;chr&gt; "", "El curs escolar passat. Una setmana senc…
$ Problema_curso22_23      &lt;chr&gt; "No", "Si", "Si", "No", "Si", "Si", "Si", "No…
$ Formacion_voz            &lt;chr&gt; "Si, vaig fer un curs fa temps", "No, mai he …
$ Medicacion               &lt;chr&gt; "Aspirina i antiinflamatoris no esteroideus",…
$ Higiene_vocal            &lt;chr&gt; "No seguesc cap rutina per a la veu", "No seg…
$ Actividades              &lt;chr&gt; "No faig cap activitat amb exigència vocal ex…
$ No_me_ecuchan            &lt;chr&gt; "Mai", "Mai", "Mai", "Gairebé sempre", "Sempr…
$ No_me_escuchan_ruido     &lt;chr&gt; "Mai", "A vegades", "Gairebé sempre", "Gaireb…
$ Alteracion_vida_social   &lt;chr&gt; "Mai", "A vegades", "A vegades", "Gairebé mai…
$ Desplazado_conversacion  &lt;chr&gt; "Mai", "Mai", "Mai", "Gairebé mai", "A vegade…
$ Rendimiento_laboral      &lt;chr&gt; "Mai", "A vegades", "Gairebé mai", "Mai", "Ga…
$ Tensar_producir_voz      &lt;chr&gt; "Mai", "A vegades", "Mai", "Mai", "A vegades"…
$ Calidad_imprevisible     &lt;chr&gt; "Mai", "Mai", "Mai", "Mai", "Gairebé sempre",…
$ Me_molesta               &lt;chr&gt; "Mai", "Mai", "Mai", "Mai", "Gairebé sempre",…
$ Minusvalia               &lt;chr&gt; "Mai", "Mai", "Mai", "Mai", "Gairebé sempre",…
$ Gente_pregunta           &lt;chr&gt; "Mai", "Mai", "Mai", "Mai", "Gairebé sempre",…</code></pre>
</div>
</div>
<p>Observamos que hay 185 respuestas y 37 variables. Vamos a limpiar los nombres de las variables y a convertir las variables categóricas en factores, a excepción de las variables “importancia_voz”, “importancia_deporte” y “dieta_saludable” que las dejamos como variables cuantitativas discretas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 185
Columns: 37
$ id                       &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…
$ importancia_voz          &lt;int&gt; 10, 10, 10, 10, 10, 10, 9, 9, 10, 10, 9, 10, …
$ sexo                     &lt;fct&gt; Femení, Femení, Masculí, Femení, Femení, Feme…
$ lugar_trabajo            &lt;fct&gt; "Palma, Llucmajor, Algaida, Santa Eugènia, Ma…
$ cuerpo_docente           &lt;fct&gt; "Formació Professional", "Educació Secundària…
$ edad                     &lt;fct&gt; Entre 36 i 50, Entre 36 i 50, Entre 36 i 50, …
$ actividas_fisica         &lt;fct&gt; Més de 150 min. per setmana, Més de 150 min. …
$ importancia_deporte      &lt;int&gt; 10, 10, 10, 8, 10, 10, 10, 7, 10, 10, 7, 9, 7…
$ calidad_sueno            &lt;fct&gt; Dorm bé i em despert descansat, Dorm bé però …
$ cafe                     &lt;fct&gt; Diàriament, Ocasionalment, Diàriament, Diària…
$ tabaco                   &lt;fct&gt; Diariament, No, No, Anteriorment (exfumador),…
$ alcohol                  &lt;fct&gt; Ocasionalment, Ocasionalment, Setmanalment, S…
$ bebida_gas               &lt;fct&gt; Mai, Ocasionalment, Diàriament, Ocasionalment…
$ dieta_saludable          &lt;int&gt; 8, 6, 9, 6, 10, 10, 8, 8, 8, 8, 9, 9, 8, 7, 7…
$ diagnostico              &lt;fct&gt; "Cap de les esmentades anteriorment", "Cap de…
$ patologia                &lt;fct&gt; "", "", "", "", "Asma, al·lergia", "", "", ""…
$ diagnostico_especialista &lt;fct&gt; No, Si, No, Si, No, Si, No, No, Si, No, No, N…
$ sintomas                 &lt;fct&gt; "Mucositat", "Fatiga vocal", "Veu ronca, esca…
$ operacion                &lt;fct&gt; No, No, No, No, No, No, No, No, Si, No, No, N…
$ tiempo_alteracion        &lt;fct&gt; No tenc cap alteració de la veu., Va començar…
$ baja_voz                 &lt;fct&gt; "No, mai he estat de baixa per un problema de…
$ baja_larga               &lt;fct&gt; "", "El curs escolar passat. Una setmana senc…
$ problema_curso22_23      &lt;fct&gt; No, Si, Si, No, Si, Si, Si, No, No, No, No, N…
$ formacion_voz            &lt;fct&gt; "Si, vaig fer un curs fa temps", "No, mai he …
$ medicacion               &lt;fct&gt; "Aspirina i antiinflamatoris no esteroideus",…
$ higiene_vocal            &lt;fct&gt; "No seguesc cap rutina per a la veu", "No seg…
$ actividades              &lt;fct&gt; "No faig cap activitat amb exigència vocal ex…
$ no_me_ecuchan            &lt;fct&gt; Mai, Mai, Mai, Gairebé sempre, Sempre, Gaireb…
$ no_me_escuchan_ruido     &lt;fct&gt; Mai, A vegades, Gairebé sempre, Gairebé sempr…
$ alteracion_vida_social   &lt;fct&gt; Mai, A vegades, A vegades, Gairebé mai, Gaire…
$ desplazado_conversacion  &lt;fct&gt; Mai, Mai, Mai, Gairebé mai, A vegades, Mai, M…
$ rendimiento_laboral      &lt;fct&gt; Mai, A vegades, Gairebé mai, Mai, Gairebé sem…
$ tensar_producir_voz      &lt;fct&gt; Mai, A vegades, Mai, Mai, A vegades, A vegade…
$ calidad_imprevisible     &lt;fct&gt; Mai, Mai, Mai, Mai, Gairebé sempre, A vegades…
$ me_molesta               &lt;fct&gt; Mai, Mai, Mai, Mai, Gairebé sempre, Mai, Gair…
$ minusvalia               &lt;fct&gt; Mai, Mai, Mai, Mai, Gairebé sempre, Mai, A ve…
$ gente_pregunta           &lt;fct&gt; Mai, Mai, Mai, Mai, Gairebé sempre, A vegades…</code></pre>
</div>
</div>
<p>Ahora, para calcular el índice de calidad de voz (VHI), vamos a seleccionar las variables desde la 28 a la 37 para convertirlas en cuantitativas discretas y a sumarlas para obtener el índice VIH.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 185
Columns: 11
$ no_me_ecuchan           &lt;dbl&gt; 0, 0, 0, 3, 4, 3, 2, 0, 1, 1, 0, 0, 1, 0, 1, 0…
$ no_me_escuchan_ruido    &lt;dbl&gt; 0, 2, 3, 3, 1, 3, 1, 0, 2, 1, 0, 2, 3, 1, 2, 0…
$ alteracion_vida_social  &lt;dbl&gt; 0, 2, 2, 1, 3, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0…
$ desplazado_conversacion &lt;dbl&gt; 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0…
$ rendimiento_laboral     &lt;dbl&gt; 0, 2, 1, 0, 3, 2, 3, 1, 0, 1, 0, 0, 1, 1, 1, 0…
$ tensar_producir_voz     &lt;dbl&gt; 0, 2, 0, 0, 2, 2, 2, 1, 1, 1, 0, 0, 2, 2, 1, 0…
$ calidad_imprevisible    &lt;dbl&gt; 0, 0, 0, 0, 3, 2, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0…
$ me_molesta              &lt;dbl&gt; 0, 0, 0, 0, 3, 0, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0…
$ minusvalia              &lt;dbl&gt; 0, 0, 0, 0, 3, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0…
$ gente_pregunta          &lt;dbl&gt; 0, 0, 0, 0, 3, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0…
$ VHI                     &lt;dbl&gt; 0, 8, 6, 8, 27, 15, 14, 4, 10, 7, 1, 2, 8, 6, …</code></pre>
</div>
</div>
<p>Por último, vamos a añadir la variable VHI al dataframe original y a eliminar las variables de la 28 a la 37.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 185
Columns: 27
$ id                       &lt;fct&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14…
$ importancia_voz          &lt;int&gt; 10, 10, 10, 10, 10, 10, 9, 9, 10, 10, 9, 10, …
$ sexo                     &lt;fct&gt; Femení, Femení, Masculí, Femení, Femení, Feme…
$ lugar_trabajo            &lt;fct&gt; "Palma, Llucmajor, Algaida, Santa Eugènia, Ma…
$ cuerpo_docente           &lt;fct&gt; "Formació Professional", "Educació Secundària…
$ edad                     &lt;fct&gt; Entre 36 i 50, Entre 36 i 50, Entre 36 i 50, …
$ actividas_fisica         &lt;fct&gt; Més de 150 min. per setmana, Més de 150 min. …
$ importancia_deporte      &lt;int&gt; 10, 10, 10, 8, 10, 10, 10, 7, 10, 10, 7, 9, 7…
$ calidad_sueno            &lt;fct&gt; Dorm bé i em despert descansat, Dorm bé però …
$ cafe                     &lt;fct&gt; Diàriament, Ocasionalment, Diàriament, Diària…
$ tabaco                   &lt;fct&gt; Diariament, No, No, Anteriorment (exfumador),…
$ alcohol                  &lt;fct&gt; Ocasionalment, Ocasionalment, Setmanalment, S…
$ bebida_gas               &lt;fct&gt; Mai, Ocasionalment, Diàriament, Ocasionalment…
$ dieta_saludable          &lt;int&gt; 8, 6, 9, 6, 10, 10, 8, 8, 8, 8, 9, 9, 8, 7, 7…
$ diagnostico              &lt;fct&gt; "Cap de les esmentades anteriorment", "Cap de…
$ patologia                &lt;fct&gt; "", "", "", "", "Asma, al·lergia", "", "", ""…
$ diagnostico_especialista &lt;fct&gt; No, Si, No, Si, No, Si, No, No, Si, No, No, N…
$ sintomas                 &lt;fct&gt; "Mucositat", "Fatiga vocal", "Veu ronca, esca…
$ operacion                &lt;fct&gt; No, No, No, No, No, No, No, No, Si, No, No, N…
$ tiempo_alteracion        &lt;fct&gt; No tenc cap alteració de la veu., Va començar…
$ baja_voz                 &lt;fct&gt; "No, mai he estat de baixa per un problema de…
$ baja_larga               &lt;fct&gt; "", "El curs escolar passat. Una setmana senc…
$ problema_curso22_23      &lt;fct&gt; No, Si, Si, No, Si, Si, Si, No, No, No, No, N…
$ formacion_voz            &lt;fct&gt; "Si, vaig fer un curs fa temps", "No, mai he …
$ medicacion               &lt;fct&gt; "Aspirina i antiinflamatoris no esteroideus",…
$ higiene_vocal            &lt;fct&gt; "No seguesc cap rutina per a la veu", "No seg…
$ actividades              &lt;fct&gt; "No faig cap activitat amb exigència vocal ex…</code></pre>
</div>
</div>
</section>
<section id="p7-el-cuidado-de-voz-mejora-la-calidad-de-la-misma-cuál-es-la-mejor-medida" class="level2">
<h2 class="anchored" data-anchor-id="p7-el-cuidado-de-voz-mejora-la-calidad-de-la-misma-cuál-es-la-mejor-medida">P7: ¿El cuidado de voz mejora la calidad de la misma? ¿Cuál es la mejor medida?</h2>
<p><strong>Grupo escuderia_ferrrari: Álvaro Velasco Sobrino, Carlos Bayes Liébana, Miquel Rivas Vanrell</strong></p>
<p>No encuentro en mi correo vuestra entrega. En todo caso hay que cruzar el score VIH con la pregunta si el participante sigue una rutina de higiene vocal.</p>
<p>Hacer un boxplot entre la higiene vocal y el score. Y luego una prueba inferencial.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="limpio_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Para facilitarnos el trabajo a la hora de hacer el test de inferencia, que en este caso será de correlación, consideramos que este es el test de inferencia más adecuado ya que nos dirá a que nivel encontramos relación entre estas variables (que es lo que se quiere responder en estas preguntas). Para ello, convertiremos las respuestas (cualitativas) en valores numéricos:</p>
<p>Lo que haremos será asignar una variable numérica a cada respuesta posible ordenada de menor a mayor según lo buena o efectiva que es la rutina que siguen (orden de prioridad). Así, para no evitar contradicciones con las respuestas lo que haremos será considerar solo 6 de estas respuestas, que son: “Mucha agua”, “Calienta y reposo”, “Calienta, reposo y mucha agua”, “Reposo”, “No rutina”, “Reposo y mucha agua”.</p>
<p>Para realizarlo, nos compararemos estas respuestas con las de otra pregunta. La pregunta será: “Ha tengut problemes de veu importants i que li han dificultat la feina al llarg del curs 2022-2023?”.</p>
<p>Lo haremos por frecuencias, es decir, calcularemos con que frecuencias alguien que no hace rutina ha tenido problemas y mediante estas frecuencias determinaremos el orden de prioridad.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   problema_curso22_23                 higiene_vocal  n
1                   No Calienta, reposo y mucha agua  1
2                   No                      Caliento  1
3                   No                    Mucha agua 43
4                   No                     No rutina 76
5                   No                        Reposo  8
6                   No           Reposo y mucha agua 20
7                   Si             Calienta y reposo  2
8                   Si Calienta, reposo y mucha agua  1
9                   Si                      Caliento  1
10                  Si                    Mucha agua 16
11                  Si                     No rutina  8
12                  Si                        Reposo  2
13                  Si           Reposo y mucha agua  6</code></pre>
</div>
</div>
<p>Ahora, debemos calcular la probabilidad de no tener enfermedad con cada una de las respuestas.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 4
   problema_curso22_23 higiene_vocal                     n Probabilidad
   &lt;fct&gt;               &lt;chr&gt;                         &lt;int&gt;        &lt;dbl&gt;
 1 No                  Calienta, reposo y mucha agua     1       0.5   
 2 No                  Caliento                          1       0.5   
 3 No                  Mucha agua                       43       0.729 
 4 No                  No rutina                        76       0.905 
 5 No                  Reposo                            8       0.8   
 6 No                  Reposo y mucha agua              20       0.769 
 7 Si                  Calienta y reposo                 2       1     
 8 Si                  Calienta, reposo y mucha agua     1       0.5   
 9 Si                  Caliento                          1       0.5   
10 Si                  Mucha agua                       16       0.271 
11 Si                  No rutina                         8       0.0952
12 Si                  Reposo                            2       0.2   
13 Si                  Reposo y mucha agua               6       0.231 </code></pre>
</div>
</div>
<p>Por tanto, lo mejor es lo que en problema_curso22_23 tenga mayor probabilidad. 1-No rutina 2-Hace reposo 3-Hace reposo y bebe mucha agua 4-Bebe mucha agua 5-Calienta, hace reposo y bebe mucha agua 6-Escalf la veu abans de començar la feina</p>
<p>Notemos que este podium no tiene sentido lógico ya que por intuición se espera que tener una rutina sea lo mejor para la voz pero no es así. Esto se puede deber a la falta de respuestas (ya que solo hay dos observaciones de los tratamientos aparentemente mejores). Es por ello, que haremos dos pruebas de inferencia, una con los resultados obtenidos en la clasificación y el otro con nuestra clasificación.</p>
<p><strong>ORDENACIÓN OBTENIDOS</strong></p>
<p>Ahora realizamos el test:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]

    Pearson's product-moment correlation

data:  VHI and higiene_vocal_num
t = -4.708, df = 181, p-value = 4.961e-06
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.4536226 -0.1945654
sample estimates:
    cor 
-0.3303 </code></pre>
</div>
</div>
<p>Esto significa que se afectan de manera opuesta y por tanto, siguiendo la lógica, esta ordenación no tiene sentido.</p>
<p><strong>ORDENACIÓN PROPIA</strong></p>
<p>Ahora realizamos el test:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]

    Pearson's product-moment correlation

data:  VHI and higiene_vocal_num
t = 4.2511, df = 181, p-value = 3.403e-05
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1633788 0.4276608
sample estimates:
     cor 
0.301295 </code></pre>
</div>
</div>
<p>Como podemos ver, al ser el resultado del test una correlación del 0.301295. Pese a ser relativamente moderada, se puede afirmar que las rutinas de higiene vocal tienen correlación con el VHI.</p>
<p><strong>Respuesta a la pregunta 7:</strong></p>
<p>Dado que la correlación es notable entre el cuidado de la voz y el mejoramiento de la misma, respondemos de forma afirmativa a esta pregunta. Para la segunda parte de la pregunta, tenemos que el método más efectivo es la unión de “Calienta, hace reposo y bebe mucha agua”.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>